language: python
python:
    - "3.6"
install:
    - pip install -r requirements.txt
    - export PYTHONPATH=$PWD
script: pytest --cov-report term-missing --cov=src/ -vv tests/
after_success:
    - codecov
