language: python
python:
    - "3.6"
install:
    - pip install -r requirements.txt
    - export PYTHONPATH=$PWD
script: pytest --cov-report term-missing --cov=src/ --cov-report html:cov_html -vv tests/
